[build]
builder = "dockerfile"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
RAILWAY_ENVIRONMENT = "production" 