[build]
builder = "dockerfile"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
RAILWAY_ENVIRONMENT = "production" 